input_dir: 
output_dir: 
interval: 8
prefix: 
start_number: 0
limit: null
crop_area:
- 0
- 180
- 640
- 640
resize_to:
  width: 640
  height: null
color_space: BGR
ext: png
use_datetime_token: true
datetime_format: '%Y%m%d_%H%M%S'
parallel_workers: 6
verbose: true
progress: true
